function wav_coeffs = wavelet_ordering(f_w,s_im, Colorednodes)
max_level = length(f_w);
N = zeros(max_level,1);
for level = 1:max_level
    N(level)= length(f_w{level});
end

% Plot Wavelet Coeffficents
Data_w = zeros(s_im);
x0 = 0;
y0 = 0;
dim = sqrt(N(max_level))/2;
temp_coeff = zeros(dim*dim,4);
temp_coeff(:,1) = f_w{max_level}(Colorednodes{max_level,1},1);
temp_coeff(:,2) = f_w{max_level}(Colorednodes{max_level,2},2);
temp_coeff(:,3) = f_w{max_level}(Colorednodes{max_level,3},3);
temp_coeff(:,4) = f_w{max_level}(Colorednodes{max_level,4},4);
xind = x0 + (1:dim);
yind = y0 + (1:dim);
% temp_coeff(:,2:4) = abs(temp_coeff(:,2:4));
% temp_coeff(:,1)= temp_coeff(:,1) /norm(temp_coeff(:,1));
Data_w(xind,yind) = reshape(temp_coeff(:,1),dim,dim);
y0 = y0+dim;
xind = x0 + (1:dim);
yind = y0 + (1:dim);
% temp_coeff(:,2)= temp_coeff(:,2) /norm(temp_coeff(:,2));
Data_w(xind,yind) = reshape(temp_coeff(:,2),dim,dim);
x0 = x0+dim;
y0 = 0;
xind = x0 + (1:dim);
yind = y0 + (1:dim);
% temp_coeff(:,3)= temp_coeff(:,3) /norm(temp_coeff(:,3));
Data_w(xind,yind) = reshape(temp_coeff(:,3),dim,dim);
y0 = y0+dim;
xind = x0 + (1:dim);
yind = y0 + (1:dim);
% temp_coeff(:,4)= temp_coeff(:,4) /norm(temp_coeff(:,4));
Data_w(xind,yind) = reshape(temp_coeff(:,4),dim,dim);

for level = (max_level-1):-1:1
    dim = sqrt(N(level))/2;
    temp_coeff = zeros(dim*dim,3);
    temp_coeff(:,1) = f_w{level}(Colorednodes{level,2},2);
    temp_coeff(:,2) = f_w{level}(Colorednodes{level,3},3);
    temp_coeff(:,3) = f_w{level}(Colorednodes{level,4},4);
    %     temp_coeff = abs(temp_coeff);
    x0 = 0;
    y0 = x0 + dim;
    xind = x0 + (1:dim);
    yind = y0 + (1:dim);
    %     temp_coeff(:,1)= temp_coeff(:,1) /norm(temp_coeff(:,1));
    Data_w(xind,yind) = reshape(temp_coeff(:,1),dim,dim);
    x0 = x0 +dim;
    y0 = 0;
    xind = x0 + (1:dim);
    yind = y0 + (1:dim);
    %     temp_coeff(:,2)= temp_coeff(:,2) /norm(temp_coeff(:,2));
    Data_w(xind,yind) = reshape(temp_coeff(:,2),dim,dim);
    y0 = y0 + dim;
    xind = x0 + (1:dim);
    yind = y0 + (1:dim);
    %     temp_coeff(:,3)= temp_coeff(:,3) /norm(temp_coeff(:,3));
    Data_w(xind,yind) = reshape(temp_coeff(:,3),dim,dim);
end
dim = sqrt(N(max_level))/2;
% tempw = Data_w;
% tempw(1:dim,1:dim) = 0;
% Data_w = Data_w - tempw;
% Data_w = rescale(Data_w) + rescale(abs(tempw));
wav_coeffs = Data_w; % the wavelet coefficients are stored in the image format
